// End-to-end: tables, DML, queries, dates and transactions through node-oracledb.

const { test, before, after, beforeEach } = require('node:test');
const assert = require('node:assert/strict');
const oracledb = require('oracledb');
const { MockOracle } = require('..');

const seed = `
  create table dept (
    id   number(4) primary key,
    name varchar2(30) not null unique
  );
  create table emp (
    id      number(6) generated by default on null as identity primary key,
    name    varchar2(40) not null,
    dept_id number(4) references dept (id),
    salary  number(8,2) check (salary > 0),
    hired   date,
    updated timestamp(3)
  );
  insert into dept values (10, 'Sales');
  insert into dept values (20, 'Engineering');
  insert into emp (name, dept_id, salary, hired) values ('Ada', 20, 9000, date '2020-01-15');
  insert into emp (name, dept_id, salary, hired) values ('Bob', 10, 5000, date '2021-06-01');
`;

let db;
let conn;
const connect = () => oracledb.getConnection({ user: 'app', password: 'oracle', connectString: db.connectString });

before(async () => {
  db = await MockOracle.start({ seed });
  conn = await connect();
});

after(async () => {
  await conn?.close();
  await db?.stop();
});

beforeEach(async () => {
  await conn.rollback();
  db.restore();
});

test('seeded tables are queryable with column metadata', async () => {
  const r = await conn.execute('select id, name, salary, hired from emp order by id', [], {
    outFormat: oracledb.OUT_FORMAT_OBJECT,
  });
  assert.deepEqual(r.rows, [
    { ID: 1, NAME: 'Ada', SALARY: 9000, HIRED: new Date(2020, 0, 15) },
    { ID: 2, NAME: 'Bob', SALARY: 5000, HIRED: new Date(2021, 5, 1) },
  ]);
  assert.equal(r.metaData[1].dbType, oracledb.DB_TYPE_VARCHAR);
  assert.equal(r.metaData[1].byteSize, 40);
  assert.equal(r.metaData[2].precision, 8);
  assert.equal(r.metaData[2].scale, 2);
  assert.equal(r.metaData[3].dbType, oracledb.DB_TYPE_DATE);
});

test('INSERT, UPDATE and DELETE report rowsAffected', async () => {
  let r = await conn.execute('insert into emp (name, dept_id, salary) values (:n, :d, :s)', { n: 'Cy', d: 20, s: 7000 });
  assert.equal(r.rowsAffected, 1);
  r = await conn.execute('update emp set salary = salary + 100 where dept_id = :d', [20]);
  assert.equal(r.rowsAffected, 2);
  r = await conn.execute('delete from emp where salary < 6000');
  assert.equal(r.rowsAffected, 1);
  r = await conn.execute('select name, salary from emp order by name');
  assert.deepEqual(r.rows, [['Ada', 9100], ['Cy', 7100]]);
});

test('joins, grouping and paging', async () => {
  await conn.execute("insert into emp (name, dept_id, salary) values ('Cy', 20, 7000)");
  const r = await conn.execute(`
    select d.name, count(*) as headcount, sum(e.salary) as total
      from dept d join emp e on e.dept_id = d.id
     group by d.name
     order by total desc`);
  assert.deepEqual(r.rows, [['Engineering', 2, 16000], ['Sales', 1, 5000]]);
  const page = await conn.execute('select name from emp order by name offset 1 rows fetch next 1 rows only');
  assert.deepEqual(page.rows, [['Bob']]);
});

test('constraint violations raise the Oracle errors', async () => {
  await assert.rejects(conn.execute("insert into dept values (10, 'Dup')"), { errorNum: 1 });
  await assert.rejects(conn.execute('insert into emp (name) values (null)'), { errorNum: 1400 });
  await assert.rejects(conn.execute("insert into emp (name, salary) values ('X', -5)"), { errorNum: 2290 });
  await assert.rejects(conn.execute("insert into dept values (30, rpad('x', 40, 'x'))"), { errorNum: 12899 });
  await assert.rejects(conn.execute('select nope from emp'), { errorNum: 904 });
});

test('uncommitted changes are private to the connection until commit', async () => {
  const other = await connect();
  try {
    await conn.execute("insert into dept values (30, 'Ops')");
    const count = async (c) => (await c.execute('select count(*) from dept')).rows[0][0];
    assert.equal(await count(conn), 3);
    assert.equal(await count(other), 2);
    await conn.commit();
    assert.equal(await count(other), 3);
    await conn.execute('delete from dept where id = 30');
    await conn.rollback();
    assert.equal(await count(conn), 3);
  } finally {
    await other.close();
  }
});

test('autoCommit makes changes visible to other connections', async () => {
  const other = await connect();
  try {
    await conn.execute("insert into dept values (40, 'Auto')", [], { autoCommit: true });
    const r = await other.execute('select name from dept where id = 40');
    assert.deepEqual(r.rows, [['Auto']]);
  } finally {
    await other.close();
  }
});

test('closing a connection rolls back its open transaction', async () => {
  const other = await connect();
  await other.execute("insert into dept values (50, 'Lost')");
  await other.close();
  const r = await conn.execute('select count(*) from dept where id = 50');
  assert.deepEqual(r.rows, [[0]]);
});

test('executeMany inserts every row', async () => {
  const rows = [
    { id: 60, name: 'A' },
    { id: 61, name: 'B' },
    { id: 62, name: 'C' },
  ];
  const r = await conn.executeMany('insert into dept (id, name) values (:id, :name)', rows, { autoCommit: true });
  assert.equal(r.rowsAffected, 3);
  const check = await conn.execute('select name from dept where id >= 60 order by id');
  assert.deepEqual(check.rows, [['A'], ['B'], ['C']]);
});

test('executeMany without binds runs the statement the requested number of times', async () => {
  await conn.execute('create table ticks (n number)');
  const r = await conn.executeMany('insert into ticks values (1)', 3);
  assert.equal(r.rowsAffected, 3);
  assert.deepEqual((await conn.execute('select count(*) from ticks')).rows, [[3]]);
  await conn.execute('drop table ticks');
});

test('JavaScript dates round-trip through DATE and TIMESTAMP columns', async () => {
  const hired = new Date(2024, 1, 29, 13, 45, 30);
  const updated = new Date(2024, 1, 29, 13, 45, 30, 123);
  await conn.execute(
    "insert into emp (name, hired, updated) values ('Dee', :hired, :updated)",
    { hired, updated },
  );
  const r = await conn.execute("select hired, updated from emp where name = 'Dee'");
  assert.deepEqual(r.rows, [[hired, updated]]);
  assert.equal(r.metaData[1].dbType, oracledb.DB_TYPE_TIMESTAMP);
  const found = await conn.execute('select name from emp where hired = :d', [hired]);
  assert.deepEqual(found.rows, [['Dee']]);
  const formatted = await conn.execute("select to_char(hired, 'YYYY-MM-DD HH24:MI:SS') from emp where name = 'Dee'");
  assert.deepEqual(formatted.rows, [['2024-02-29 13:45:30']]);
});

test('snapshot and restore', async () => {
  await conn.execute("insert into dept values (70, 'Kept')", [], { autoCommit: true });
  const snap = db.snapshot();
  await conn.execute('delete from dept', [], { autoCommit: true });
  db.restore(snap);
  let r = await conn.execute('select count(*) from dept');
  assert.deepEqual(r.rows, [[3]]);
  db.restore();
  r = await conn.execute('select count(*) from dept');
  assert.deepEqual(r.rows, [[2]]);
});

test('DDL and runScript', async () => {
  db.runScript("create table notes (id number, body varchar2(100)); insert into notes values (1, 'hi')");
  let r = await conn.execute('select body from notes');
  assert.deepEqual(r.rows, [['hi']]);
  await conn.execute('drop table notes');
  await assert.rejects(conn.execute('select * from notes'), { errorNum: 942 });
  assert.throws(() => db.runScript('insert into nowhere values (1)'), /ORA-00942/);
});
